version: '2'
services:
  opacache:
    build: ./opacache/
    container_name: opacache
    ports:
     - "3333:3333"
    networks:
      - opaCacheNetwork
networks:
  opaCacheNetwork:
    driver: "bridge"
